### ISSUE TITLE
Question: Why is MatchedRoutePathParam random?

### ISSUE THREAD

**Issue by mr-karan** [fasthttp/router#21]
`MatchedRoutePathParam` is used to store the original path registered by the user in `ctx.UserValues`. From the [code](https://github.com/fasthttp/router/blob/master/router.go#L90), I found that this variable is defined with some random byte strings at runtime. What's the reasoning behind keeping this variable as random? Side effect of this is any downstream user of the library, including arbitrary middleware/wrappers need to now import this variable everywhere. 

Additionally, do you think passing this variable from the user makes sense?

Thanks!

**Comment by savsgio** [comment]
Hi @mr-karan,

The `MatchedRoutePathParam`  has a random value to force the users always use the variable and not the value directly because it's an internal value of the router, like a constant. Also the random value is for try not override the custom user values in the context.

The side effect that you say, i think so it shouldn't be a problem, because you will be obligated to use the variable and if the value of that changes, you won't have to change it in your code. You could consider as a best practice.

**Comment by mr-karan** [comment]
Got it. Yes that makes sense now. Thanks for answering! 👍
