### ISSUE TITLE
optional parameter get request

### ISSUE THREAD

**Issue by Milerius** [fasthttp/router#8]
Hello,

Is this possible to define optional parameter like 

```
/foo/:barvalue/?:baroption=1 // < baroption is optional we can say /foo/value and /foo/value/?option=1
```

What is the best way to achieve that with the router ?

```
Translate something like that with the framework ?
GET /foo?option=value&bar=otheroption 
```

**Comment by savsgio** [comment]
At now, it's not possible to do that. If you want to do that you must define all urls you would need.
So you could make a PR adding this enhancement.

**Comment by savsgio** [comment]
Hi @Milerius,

I read again your issue and query params are not belong to the path, so it's not responsability of router foresee these args, you must be recover it with `ctx.QueryArgs().Peek("<KEY>")`, because the query params are always optionals.

But the optional arguments belonger the path are not supported yet.

**Comment by Milerius** [comment]
Thank's a lot
